"""Bundle the multi-file Dash app into a single YourName_ProjectName.py.

Strips intra-project imports, keeps one `from __future__` at top,
and fixes BASE_DIR so the XLSX/cache resolve next to the single file.
"""

from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent

FILES = [
    "utils/formatting.py",
    "utils/data_processing.py",
    "utils/calculations.py",
    "components/theme.py",
    "components/kpi_cards.py",
    "components/sidebar.py",
    "components/world_map.py",
    "components/charts.py",
    "components/tables.py",
    "pages/executive_overview.py",
    "pages/profit_leakage.py",
    "pages/customer_value.py",
    "pages/product_analysis.py",
    "app.py",
]

STRIP_PATTERNS = [
    r"^from utils\..*",
    r"^from components\..*",
    r"^from pages import.*",
    r"^from pages\..*",
    r"^from \.data_processing import.*",
    r"^from \.theme import.*",
    r"^from __future__ import.*",
]


def clean(text: str, path: str) -> str:
    out = []
    skipping = False
    skip_dup = False
    for line in text.splitlines():
        s = line.strip()
        if skipping:
            if ")" in s:
                skipping = False
            continue
        # calculations.py re-defines calculate_profit_leakage as a thin wrapper
        # over data_processing's same-named function; inlined that would recurse,
        # so drop the duplicate (the original stays available under its name).
        if path == "utils/calculations.py" and s.startswith("def calculate_profit_leakage("):
            skip_dup = True
            continue
        if skip_dup:
            if s.startswith("return "):
                skip_dup = False
            continue
        if any(re.match(p, s) for p in STRIP_PATTERNS):
            if s.endswith("("):
                skipping = True
            continue
        out.append(line)
    body = "\n".join(out).strip("\n")
    if path.startswith("pages/"):
        stem = Path(path).stem  # each page defines layout(); namespace them
        body = body.replace("def layout(", f"def {stem}_layout(", 1)
    if path == "app.py":
        for stem in ("executive_overview", "profit_leakage",
                     "customer_value", "product_analysis"):
            body = body.replace(f"{stem}.layout(", f"{stem}_layout(")
    if path == "utils/data_processing.py":
        body = body.replace(
            "BASE_DIR = Path(__file__).resolve().parent.parent",
            "BASE_DIR = Path(__file__).resolve().parent",
        )
    return body


parts = [
    '"""ProfitLens — Global E-Commerce Profit Leakage & Customer Value Analytics.',
    "Single-file submission bundle (generated by build_single_file.py).",
    "Run:  python YourName_ProjectName.py   ->  http://127.0.0.1:8050",
    '"""',
    "from __future__ import annotations",
]
for f in FILES:
    parts.append(f"\n# {'=' * 70}\n# {f}\n# {'=' * 70}\n")
    parts.append(clean((ROOT / f).read_text(encoding="utf-8"), f))

out = "\n".join(parts) + "\n"
(ROOT / "YourName_ProjectName.py").write_text(out, encoding="utf-8")
print(f"wrote YourName_ProjectName.py ({len(out) / 1024:.0f} KB)")
