"""ProfitLens — Global E-Commerce Profit Leakage & Customer Value Analytics.
Single-file submission bundle (generated by build_single_file.py).
Run:  python dashboard.py   ->  http://127.0.0.1:8050
"""
from __future__ import annotations
import os as _os
import sys as _sys
# Keep the script directory off sys.path so this file works under any
# filename (e.g. code.py would otherwise shadow the stdlib module).
_sys.path = [
    p for p in _sys.path
    if _os.path.abspath(p or '.') != _os.path.dirname(_os.path.abspath(__file__))
]

# ======================================================================
# utils/formatting.py
# ======================================================================

"""USD + number formatting helpers (single source of truth for UI)."""



def fmt_usd(n: float, decimals: int = 2) -> str:
    """$1,234.56 style, with minus sign for negatives."""
    try:
        v = float(n)
    except (TypeError, ValueError):
        return "$0.00"
    sign = "-" if v < 0 else ""
    return f"{sign}${abs(v):,.{decimals}f}"


def fmt_usd_compact(n: float) -> str:
    """$4.2M / $312.5K / $980 style for KPI cards and axes."""
    try:
        v = float(n)
    except (TypeError, ValueError):
        return "$0"
    sign = "-" if v < 0 else ""
    a = abs(v)
    if a >= 1_000_000_000:
        return f"{sign}${a / 1_000_000_000:.2f}B"
    if a >= 1_000_000:
        return f"{sign}${a / 1_000_000:.2f}M"
    if a >= 1_000:
        return f"{sign}${a / 1_000:.1f}K"
    return f"{sign}${a:,.0f}"


def fmt_int(n) -> str:
    try:
        return f"{int(round(float(n))):,}"
    except (TypeError, ValueError):
        return "0"


def fmt_pct(n: float, decimals: int = 1) -> str:
    try:
        return f"{float(n):.{decimals}f}%"
    except (TypeError, ValueError):
        return "0.0%"

# ======================================================================
# utils/data_processing.py
# ======================================================================

"""Dataset loading (once) + reusable Pandas aggregations.

Dataset: Global E-Commerce Dataset (+1M records, 2024-2026), XLSX at repo root.
Financial values are USD.

Strategy:
- Needed columns only (keeps memory down).
- First run converts XLSX -> data/processed.parquet (fast Calamine engine).
- Subsequent runs load the parquet cache in seconds.
- All pages share ONE loaded dataframe + precomputed aggregates
  (see get_aggregates); never reload CSV per page.

Leakage definitions (all computed from the dataset, no hardcoded totals):
- Discounts        = SUM(discount_amount_usd)
- Returns/Refunds  = SUM(total_price_usd) WHERE order_status == 'Returned'
- Shipping costs   = SUM(shipping_cost_usd)
- Failed delivery  = SUM(shipping_cost_usd) WHERE delivery_status == 'Failed'
                     (memo subset of shipping; shown separately, and the
                     waterfall splits shipping into successful vs failed so
                     nothing is double counted)
- Payment fees     = SUM(total_price_usd * rate[ payment_method ]) using
                     documented per-method estimates (dataset has no fee
                     column). Labelled "Estimated" in the UI.
"""


from pathlib import Path
import pandas as pd
import numpy as np

BASE_DIR = Path(__file__).resolve().parent
XLSX_CANDIDATES = [
    BASE_DIR / "ecommerce_dataset_+1m.xlsx",
    BASE_DIR / "data" / "ecommerce_dataset_+1m.xlsx",
]
CACHE_PATH = BASE_DIR / "data" / "processed.parquet"

NEEDED_COLS = [
    "order_id", "order_date", "order_status", "order_priority",
    "customer_id", "customer_name", "customer_segment", "country", "city",
    "product_id", "product_name", "category",
    "unit_price_usd", "quantity", "discount_percent", "discount_amount_usd",
    "total_price_usd", "cost_usd", "profit_usd", "profit_margin_percent", "tax_usd",
    "shipping_method", "shipping_cost_usd", "delivery_days",
    "shipping_country", "delivery_status",
    "payment_method", "payment_status",
    "coupon_used", "return_reason", "rating",
]

# Documented payment-fee estimates by method (dataset has no fee column).
PAYMENT_FEE_RATES = {
    "Credit Card": 0.022,
    "Debit Card": 0.018,
    "PayPal": 0.025,
    "Apple Pay": 0.020,
    "Bank Transfer": 0.010,
}
DEFAULT_FEE_RATE = 0.018


def _find_xlsx() -> Path | None:
    for p in XLSX_CANDIDATES:
        if p.exists():
            return p
    # fallback: any large xlsx at root
    for p in BASE_DIR.glob("*.xlsx"):
        return p
    return None


def _enrich(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    df["order_date"] = pd.to_datetime(df["order_date"], errors="coerce")
    df["year_month"] = df["order_date"].dt.to_period("M").astype(str)
    df["is_returned"] = df["order_status"].eq("Returned")
    df["is_failed_delivery"] = df["delivery_status"].eq("Failed")
    rates = df["payment_method"].map(PAYMENT_FEE_RATES).fillna(DEFAULT_FEE_RATE)
    df["payment_fee_est_usd"] = (df["total_price_usd"].fillna(0) * rates).round(2)
    # successful vs failed shipping split (no double counting)
    df["shipping_success_usd"] = np.where(
        df["is_failed_delivery"], 0.0, df["shipping_cost_usd"].fillna(0)
    )
    df["shipping_failed_usd"] = np.where(
        df["is_failed_delivery"], df["shipping_cost_usd"].fillna(0), 0.0
    )
    return df


def load_dataset(force_rebuild: bool = False, sample_n: int | None = None) -> pd.DataFrame:
    """Load the dataset once. Uses parquet cache when available."""
    if CACHE_PATH.exists() and not force_rebuild and sample_n is None:
        df = pd.read_parquet(CACHE_PATH)
        return df
    xlsx = _find_xlsx()
    if xlsx is None:
        raise FileNotFoundError(
            "Dataset XLSX not found. Place 'ecommerce_dataset_+1m.xlsx' at repo root or data/."
        )
    read_kwargs: dict = {"engine": "calamine", "usecols": NEEDED_COLS}
    if sample_n is not None:
        read_kwargs["nrows"] = sample_n
    df = pd.read_excel(xlsx, **read_kwargs)
    df = _enrich(df)
    if sample_n is None:
        CACHE_PATH.parent.mkdir(parents=True, exist_ok=True)
        df.to_parquet(CACHE_PATH, index=False)
    return df


# ---------------------------------------------------------------- calculations
def calculate_totals(df: pd.DataFrame) -> dict:
    revenue = float(df["total_price_usd"].sum())
    gross_profit = float(df["profit_usd"].sum())
    shipping = float(df["shipping_cost_usd"].sum())
    fees = float(df["payment_fee_est_usd"].sum())
    net_profit = gross_profit - shipping - fees
    orders = int(df["order_id"].nunique())
    aov = revenue / orders if orders else 0.0
    leakage = calculate_profit_leakage(df)
    return {
        "revenue": revenue,
        "gross_profit": gross_profit,
        "net_profit": net_profit,
        "orders": orders,
        "aov": aov,
        "shipping": shipping,
        "fees": fees,
        "leakage_total": leakage["total"],
        "leakage_pct": (leakage["total"] / revenue * 100) if revenue else 0.0,
    }


def calculate_profit_leakage(df: pd.DataFrame) -> dict:
    revenue = float(df["total_price_usd"].sum())
    discounts = float(df["discount_amount_usd"].sum())
    returns = float(df.loc[df["is_returned"], "total_price_usd"].sum())
    shipping = float(df["shipping_cost_usd"].sum())
    failed = float(df.loc[df["is_failed_delivery"], "shipping_cost_usd"].sum())
    shipping_success = shipping - failed
    fees = float(df["payment_fee_est_usd"].sum())
    total = discounts + returns + shipping + fees  # failed is memo subset of shipping
    def pct(x):
        return (x / revenue * 100) if revenue else 0.0
    return {
        "discounts": discounts,
        "returns": returns,
        "shipping": shipping,
        "shipping_success": shipping_success,
        "failed": failed,
        "fees": fees,
        "total": total,
        "discounts_pct": pct(discounts),
        "returns_pct": pct(returns),
        "shipping_pct": pct(shipping),
        "failed_pct": pct(failed),
        "fees_pct": pct(fees),
        "total_pct": pct(total),
        "revenue": revenue,
    }


def calculate_trend(df: pd.DataFrame) -> pd.DataFrame:
    g = (
        df.dropna(subset=["order_date"])
        .groupby("year_month", as_index=False)
        .agg(revenue=("total_price_usd", "sum"), profit=("profit_usd", "sum"),
             orders=("order_id", "nunique"))
        .sort_values("year_month")
    )
    return g


def calculate_country_profit(df: pd.DataFrame) -> pd.DataFrame:
    g = (
        df.groupby("country", as_index=False)
        .agg(revenue=("total_price_usd", "sum"), profit=("profit_usd", "sum"),
             orders=("order_id", "nunique"))
    )
    g["margin"] = np.where(g["revenue"] != 0, g["profit"] / g["revenue"] * 100, 0.0)
    return g.sort_values("profit", ascending=False)


def calculate_shipping_metrics(df: pd.DataFrame) -> pd.DataFrame:
    g = (
        df.groupby("shipping_country", as_index=False)
        .agg(
            shipping_cost=("shipping_cost_usd", "sum"),
            orders=("order_id", "nunique"),
            avg_days=("delivery_days", "mean"),
            failed_orders=("is_failed_delivery", "sum"),
        )
    )
    g["failed_pct"] = np.where(
        g["orders"] != 0, g["failed_orders"] / g["orders"] * 100, 0.0
    )
    return g.sort_values("shipping_cost", ascending=False)


def calculate_category_metrics(df: pd.DataFrame) -> pd.DataFrame:
    g = (
        df.groupby("category", as_index=False)
        .agg(
            revenue=("total_price_usd", "sum"),
            profit=("profit_usd", "sum"),
            orders=("order_id", "nunique"),
            avg_discount=("discount_percent", "mean"),
        )
    )
    g["margin"] = np.where(g["revenue"] != 0, g["profit"] / g["revenue"] * 100, 0.0)
    return g.sort_values("profit", ascending=False)


def calculate_product_metrics(df: pd.DataFrame, top_n: int | None = None) -> pd.DataFrame:
    g = (
        df.groupby(["product_name", "category"], as_index=False)
        .agg(
            revenue=("total_price_usd", "sum"),
            profit=("profit_usd", "sum"),
            orders=("order_id", "nunique"),
            avg_discount=("discount_percent", "mean"),
            returns=("is_returned", "sum"),
        )
    )
    g["margin"] = np.where(g["revenue"] != 0, g["profit"] / g["revenue"] * 100, 0.0)
    g["return_rate"] = np.where(g["orders"] != 0, g["returns"] / g["orders"] * 100, 0.0)
    g = g.sort_values("profit", ascending=False)
    if top_n is not None:
        # keep top winners + worst losers for a balanced ranking chart
        half = max(1, top_n // 2)
        g = pd.concat([g.head(half), g.tail(top_n - half)]).drop_duplicates()
        g = g.sort_values("profit", ascending=False)
    return g


def calculate_customer_metrics(df: pd.DataFrame) -> pd.DataFrame:
    grp = df.groupby("customer_id", as_index=False).agg(
        customer_name=("customer_name", "first"),
        country=("country", "first"),
        city=("city", "first"),
        raw_segment=("customer_segment", "first"),
        revenue=("total_price_usd", "sum"),
        profit=("profit_usd", "sum"),
        orders=("order_id", "nunique"),
        returns=("is_returned", "sum"),
    )
    grp["aov"] = np.where(grp["orders"] != 0, grp["revenue"] / grp["orders"], 0.0)
    grp["return_rate"] = np.where(grp["orders"] != 0, grp["returns"] / grp["orders"] * 100, 0.0)
    grp["clv"] = grp["profit"]  # CLV proxy = lifetime profit contributed
    # Value segments from actual profitability tertiles -> High / Medium / Low
    try:
        grp["segment"] = pd.qcut(grp["profit"], q=3, labels=["Low", "Medium", "High"])
    except ValueError:
        lo, hi = grp["profit"].quantile(0.33), grp["profit"].quantile(0.66)
        grp["segment"] = np.where(
            grp["profit"] >= hi, "High",
            np.where(grp["profit"] >= lo, "Medium", "Low"),
        )
    grp["segment"] = grp["segment"].astype(str)
    return grp


def discount_margin_sample(df: pd.DataFrame, n: int = 5000, seed: int = 42) -> pd.DataFrame:
    cols = ["discount_percent", "profit_margin_percent", "product_name", "category",
            "total_price_usd", "profit_usd"]
    sub = df[cols].dropna()
    if len(sub) > n:
        sub = sub.sample(n, random_state=seed)
    return sub


def get_aggregates(df: pd.DataFrame) -> dict:
    """Compute every page-level aggregate ONCE; pages only read this dict."""
    totals = calculate_totals(df)
    leakage = calculate_profit_leakage(df)
    return {
        "totals": totals,
        "leakage": leakage,
        "trend": calculate_trend(df),
        "country": calculate_country_profit(df),
        "shipping": calculate_shipping_metrics(df),
        "category": calculate_category_metrics(df),
        "products": calculate_product_metrics(df),
        "products_ranked": calculate_product_metrics(df, top_n=16),
        "customers": calculate_customer_metrics(df),
        "scatter": discount_margin_sample(df),
    }

# ======================================================================
# utils/calculations.py
# ======================================================================

"""Thin wrappers so pages read like the spec's example API."""


import pandas as pd



def calculate_total_revenue(df: pd.DataFrame) -> float:
    return float(df["total_price_usd"].sum())


def calculate_total_profit(df: pd.DataFrame) -> float:
    totals = calculate_totals(df)
    return totals["net_profit"]




def calculate_customer_metrics_df(df: pd.DataFrame) -> pd.DataFrame:
    return calculate_customer_metrics(df)


def calculate_product_metrics_df(df: pd.DataFrame) -> pd.DataFrame:
    return calculate_product_metrics(df)


def calculate_country_profit_df(df: pd.DataFrame) -> pd.DataFrame:
    return calculate_country_profit(df)


def calculate_shipping_metrics_df(df: pd.DataFrame) -> pd.DataFrame:
    return calculate_shipping_metrics(df)


def calculate_category_metrics_df(df: pd.DataFrame) -> pd.DataFrame:
    return calculate_category_metrics(df)


def calculate_trend_df(df: pd.DataFrame) -> pd.DataFrame:
    return calculate_trend(df)

# ======================================================================
# components/theme.py
# ======================================================================

"""Shared pastel palette + Plotly template (mirrors React reference)."""

PALETTE = {
    "green": "#9abe30",
    "green_light": "#f0facc",
    "green_mid": "#b8d840",
    "blue": "#6ec8f0",
    "blue_light": "#e2f5ff",
    "blue_pale": "#c0eaff",
    "lavender": "#c0b4f0",
    "lavender_light": "#efeafd",
    "pink": "#ed9ac1",
    "pink_deep": "#c8608a",
    "pink_light": "#fce4f0",
    "yellow": "#fff680",
    "yellow_deep": "#d4b800",
    "yellow_light": "#fffde0",
    "bg": "#fdfaf6",
    "card": "#ffffff",
    "border": "#eceacc",
    "text": "#2C2E45",
    "text_s": "#5A5C72",
    "text_m": "#9497B0",
    "gray_nodata": "#edeef3",
}

# Map bucket fills required by the spec
MAP_NEGATIVE = "#f4c4d0"   # pastel pink
MAP_LOW = "#d8ecfc"        # light pastel blue
MAP_MEDIUM = "#b0c8f4"     # pastel blue
MAP_HIGH = "#c0b4f0"       # pastel lavender
MAP_NODATA = "#edeef3"     # very light gray

PROFIT_COLORSCALE = [
    [0.0, MAP_NEGATIVE],
    [0.18, MAP_NEGATIVE],
    [0.18, MAP_LOW],
    [0.45, MAP_LOW],
    [0.45, MAP_MEDIUM],
    [0.72, MAP_MEDIUM],
    [0.72, MAP_HIGH],
    [1.0, MAP_HIGH],
]

SHIPPING_COLORSCALE = [
    [0.0, "#e2f5ff"],
    [0.35, "#b8d8f8"],
    [0.65, "#8fbdf0"],
    [1.0, "#6ea8e8"],
]

SEGMENT_COLORS = {"High": "#9abe30", "Medium": "#6ec8f0", "Low": "#c8608a"}


def base_layout(title: str = "", height: int = 260):
    return dict(
        title=dict(text=title, font=dict(size=13, color=PALETTE["text"])) if title else {},
        paper_bgcolor="white",
        plot_bgcolor="white",
        height=height,
        margin=dict(l=8, r=8, t=28 if title else 8, b=8),
        font=dict(family="Inter, system-ui, sans-serif", size=11, color=PALETTE["text_s"]),
        xaxis=dict(gridcolor="#f0f2f8", zeroline=False),
        yaxis=dict(gridcolor="#f0f2f8", zeroline=False),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1,
                    font=dict(size=10)),
        hoverlabel=dict(bgcolor="white", font_size=11),
    )

# ======================================================================
# components/kpi_cards.py
# ======================================================================

"""Reusable KPI / card components."""


from dash import html



KPI_GRADIENTS = {
    "revenue": ("#ffd6e7", "#ffe8f2", "#c8608a"),
    "orders": ("#e0eea3", "#eef4c4", "#6e9a10"),
    "profit": ("#c4faf8", "#ddfdf9", "#10a8a4"),
    "aov": ("#fcc2ff", "#fde0ff", "#b020c0"),
    "leakage": ("#fff4b7", "#fffad6", "#c8a000"),
    "green": ("#e4f3c4", "#f2fae2", "#6e9a10"),
    "blue": ("#d9efff", "#eef7ff", "#3d8fd1"),
    "pink": ("#ffd6e7", "#fff0f6", "#c8608a"),
    "yellow": ("#fff4b7", "#fffde8", "#a88f00"),
}


def kpi_card(label: str, value: str, sub: str = "", kind: str = "green"):
    grad_from, grad_to, accent = KPI_GRADIENTS.get(kind, KPI_GRADIENTS["green"])
    return html.Div(
        className="kpi-card",
        style={
            "background": f"linear-gradient(135deg, {grad_from} 0%, {grad_to} 100%)",
            "border": f"1px solid {accent}22",
        },
        children=[
            html.Div(label.upper(), className="kpi-label"),
            html.Div(value, className="kpi-value"),
            html.Div(sub, className="kpi-sub") if sub else None,
        ],
    )


def kpi_row_from_totals(totals: dict):
    return html.Div(
        className="kpi-row",
        children=[
            kpi_card("Total Revenue", fmt_usd_compact(totals["revenue"]),
                     "All orders · USD", kind="revenue"),
            kpi_card("Total Orders", fmt_int(totals["orders"]),
                     "Transactions", kind="orders"),
            kpi_card("Net Profit", fmt_usd_compact(totals["net_profit"]),
                     "Gross profit − shipping − fees", kind="profit"),
            kpi_card("Average Order Value", fmt_usd_compact(totals["aov"]),
                     "Per transaction", kind="aov"),
            kpi_card("Profit Leakage", fmt_usd_compact(totals["leakage_total"]),
                     f"{fmt_pct(totals['leakage_pct'])} of revenue", kind="leakage"),
        ],
    )


def summary_card(title: str, value: str, sub: str, kind: str = "blue"):
    grad_from, grad_to, accent = KPI_GRADIENTS.get(kind, KPI_GRADIENTS["blue"])
    return html.Div(
        className="summary-card",
        style={
            "background": f"linear-gradient(135deg, {grad_from}, {grad_to})",
            "border": f"1px solid {accent}22",
        },
        children=[
            html.Div(title.upper(), className="summary-title"),
            html.Div(value, className="summary-value"),
            html.Div(sub, className="summary-sub", style={"color": accent}),
        ],
    )


def card(title: str, subtitle: str = "", children=None):
    return html.Div(
        className="card",
        children=[
            html.Div(title, className="card-title"),
            html.Div(subtitle, className="card-sub") if subtitle else None,
            html.Div(children=children, className="card-body"),
        ],
    )

# ======================================================================
# components/sidebar.py
# ======================================================================

"""Sidebar + header (persistent navigation, 4 pages)."""


from dash import html, dcc

NAV = [
    {"path": "/", "label": "Executive Overview", "dot": "#9abe30"},
    {"path": "/leakage", "label": "Profit Leakage", "dot": "#c8608a"},
    {"path": "/customers", "label": "Customer Value", "dot": "#6ec8f0"},
    {"path": "/products", "label": "Product Analysis", "dot": "#d4b800"},
]


def sidebar(active_path: str):
    links = []
    for item in NAV:
        active = (active_path or "/") == item["path"]
        links.append(
            dcc.Link(
                href=item["path"],
                className="nav-link" + (" active" if active else ""),
                children=[
                    html.Span(className="nav-dot",
                              style={"background": item["dot"],
                                     "opacity": 1 if active else 0.45}),
                    html.Span(item["label"]),
                    html.Span(className="nav-bar") if active else None,
                ],
            )
        )
    return html.Aside(
        className="sidebar",
        children=[
            html.Div(
                className="brand",
                children=[
                    html.Div(className="brand-mark"),
                    html.Div(children=[
                        html.Div("ProfitLens", className="brand-name"),
                        html.Div("ANALYTICS SUITE", className="brand-sub"),
                    ]),
                ],
            ),
            html.Nav(
                className="nav",
                children=[html.Div("Dashboard", className="nav-heading")] + links,
            ),
            html.Div(
                className="sidebar-footer",
                children=[
                    html.Div(
                        className="live-badge",
                        children=[
                            html.Span(className="live-dot"),
                            html.Span("Live Data · USD"),
                        ],
                    ),
                    html.Div(
                        className="user-row",
                        children=[
                            html.Div("A", className="avatar"),
                            html.Div(children=[
                                html.Div("Admin", className="user-name"),
                                html.Div("Global E-Commerce · 2024–2026",
                                        className="user-email"),
                            ]),
                        ],
                    ),
                ],
            ),
        ],
    )


def page_header(title: str, crumb: str):
    return html.Header(
        className="topbar",
        children=[
            html.Div(children=[
                html.Div(f"ProfitLens / {crumb}", className="crumb"),
                html.Div(title, className="page-title"),
            ]),
            html.Div("Global E-Commerce Dataset · Values in USD",
                     className="topbar-right"),
        ],
    )

# ======================================================================
# components/world_map.py
# ======================================================================

"""Plotly world choropleths (country-fill, NOT bubbles)."""


import numpy as np
import plotly.graph_objects as go



def profit_world_map(country_df) -> go.Figure:
    """Country fill = profit. Negative pink / low-med-high blue-lavender."""
    df = country_df.copy()
    pos = df.loc[df["profit"] > 0, "profit"]
    lo, hi = (float(pos.quantile(0.33)), float(pos.quantile(0.66))) if len(pos) else (0.0, 1.0)
    if hi <= lo:
        hi = lo + 1.0

    custom = np.stack([
        df["revenue"].values,
        df["profit"].values,
        df["margin"].values,
        df["orders"].values,
    ], axis=-1)

    fig = go.Figure(go.Choropleth(
        locations=df["country"],
        locationmode="country names",
        z=df["profit"],
        zmin=min(0.0, float(df["profit"].min())) if len(df) else 0,
        zmax=float(df["profit"].max()) if len(df) else 1,
        colorscale=PROFIT_COLORSCALE,
        marker_line_color="white",
        marker_line_width=0.6,
        colorbar=dict(
            title=dict(text="Profit (USD)", font=dict(size=10)),
            tickprefix="$", tickfont=dict(size=9),
            thickness=7, len=0.5, y=0.5, x=1.0,
            outlinewidth=0,
        ),
        customdata=custom,
        hovertemplate=(
            "<b>%{location}</b><br>"
            "Revenue: $%{customdata[0]:,.0f}<br>"
            "Profit: $%{customdata[1]:,.0f}<br>"
            "Profit Margin: %{customdata[2]:.1f}%<br>"
            "Orders: %{customdata[3]:,.0f}<extra></extra>"
        ),
    ))
    fig.update_layout(**base_layout(height=420))
    fig.update_layout(
        autosize=True,
        margin=dict(l=0, r=0, t=0, b=0),
        geo=dict(
            scope="world",
            showframe=False, showcoastlines=True, coastlinecolor="#d5dae5",
            showland=True, landcolor=MAP_NODATA,
            showocean=True, oceancolor="#f6f8fc",
            projection_type="equirectangular",
            lonaxis=dict(range=[-180, 180]),
            lataxis=dict(range=[-90, 90]),
            domain=dict(x=[0, 1], y=[0, 1]),
        ),
        annotations=[dict(
            text=f"Low ≤ ${lo:,.0f} · Medium ≤ ${hi:,.0f} · High > ${hi:,.0f} · Pink = negative",
            x=0.01, y=0.01, xref="paper", yref="paper",
            showarrow=False, font=dict(size=9, color=PALETTE["text_m"]),
        )],
    )
    # Interactive geographic viewport: wheel zoom + drag pan stay inside the
    # card; double-click resets. (Plotly Geo has no `fixed` property, so
    # container fixity is enforced via the .map-viewport CSS below.)
    fig.update_geos(projection_type="equirectangular")
    return fig


def shipping_world_map(ship_df) -> go.Figure:
    """Country fill = total shipping cost (USD)."""
    df = ship_df.copy()
    custom = np.stack([
        df["shipping_cost"].values,
        df["orders"].values,
        df["failed_pct"].values,
        df["avg_days"].values,
    ], axis=-1)
    fig = go.Figure(go.Choropleth(
        locations=df["shipping_country"],
        locationmode="country names",
        z=df["shipping_cost"],
        colorscale=SHIPPING_COLORSCALE,
        marker_line_color="white",
        marker_line_width=0.6,
        colorbar=dict(
            title=dict(text="Shipping (USD)", font=dict(size=10)),
            tickprefix="$", tickfont=dict(size=9),
            thickness=7, len=0.5, y=0.5, x=1.0,
            outlinewidth=0,
        ),
        customdata=custom,
        hovertemplate=(
            "<b>%{location}</b><br>"
            "Shipping Cost: $%{customdata[0]:,.0f}<br>"
            "Orders: %{customdata[1]:,.0f}<br>"
            "Failed Delivery: %{customdata[2]:.1f}%<br>"
            "Avg Delivery: %{customdata[3]:.1f} days<extra></extra>"
        ),
    ))
    fig.update_layout(**base_layout(height=480))
    fig.update_layout(
        autosize=True,
        margin=dict(l=0, r=0, t=0, b=0),
        geo=dict(
            scope="world",
            showframe=False, showcoastlines=True, coastlinecolor="#d5dae5",
            showland=True, landcolor=MAP_NODATA,
            showocean=True, oceancolor="#f4f7fb",
            projection_type="equirectangular",
            lonaxis=dict(range=[-180, 180]),
            lataxis=dict(range=[-90, 90]),
            domain=dict(x=[0, 1], y=[0, 1]),
        ),
    )
    # Same interactive viewport behavior as the profit map above.
    fig.update_geos(projection_type="equirectangular")
    return fig

# ======================================================================
# components/charts.py
# ======================================================================

"""Shared Plotly chart builders (pastel, USD, interactive hovers)."""


import numpy as np
import plotly.express as px
import plotly.graph_objects as go



def revenue_profit_trend(trend_df) -> go.Figure:
    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=trend_df["year_month"], y=trend_df["revenue"],
        mode="lines", name="Revenue",
        line=dict(color=PALETTE["pink_deep"], width=2.5),
        fill="tozeroy", fillcolor="rgba(237,154,193,0.18)",
        hovertemplate="Revenue: $%{y:,.0f}<extra>%{x}</extra>",
    ))
    fig.add_trace(go.Scatter(
        x=trend_df["year_month"], y=trend_df["profit"],
        mode="lines", name="Profit",
        line=dict(color=PALETTE["green"], width=2.5),
        fill="tozeroy", fillcolor="rgba(224,239,112,0.30)",
        hovertemplate="Profit: $%{y:,.0f}<extra>%{x}</extra>",
    ))
    fig.update_layout(**base_layout(title="", height=410))
    fig.update_layout(
        autosize=True,
        margin=dict(l=48, r=12, t=36, b=44),
        xaxis_title="", yaxis_title="",
        yaxis_tickprefix="$",
        xaxis_tickangle=-30, xaxis_tickfont=dict(size=9),
    )
    return fig


def category_profit_bars(cat_df) -> go.Figure:
    colors = [PALETTE["pink"] if p < 0 else PALETTE["green"] for p in cat_df["profit"]]
    fig = go.Figure(go.Bar(
        x=cat_df["category"], y=cat_df["profit"],
        marker_color=colors, marker_line_width=0,
        text=[f"${v:,.0f}" for v in cat_df["profit"]],
        textposition="outside", textfont=dict(size=9),
        hovertemplate="%{x}<br>Profit: $%{y:,.0f}<extra></extra>",
        name="Profit",
    ))
    fig.update_layout(**base_layout(height=240))
    fig.update_layout(yaxis_tickprefix="$")
    return fig


def category_revenue_profit(cat_df) -> go.Figure:
    fig = go.Figure()
    fig.add_trace(go.Bar(
        x=cat_df["category"], y=cat_df["revenue"], name="Revenue",
        marker_color=PALETTE["blue_pale"],
        hovertemplate="%{x}<br>Revenue: $%{y:,.0f}<extra></extra>",
    ))
    colors = [PALETTE["pink"] if p < 0 else PALETTE["green"] for p in cat_df["profit"]]
    fig.add_trace(go.Bar(
        x=cat_df["category"], y=cat_df["profit"], name="Profit",
        marker_color=colors,
        hovertemplate="%{x}<br>Profit: $%{y:,.0f}<extra></extra>",
    ))
    fig.update_layout(**base_layout(height=260))
    fig.update_layout(barmode="group", yaxis_tickprefix="$",
                      xaxis_tickfont=dict(size=9))
    return fig


def product_ranking_bars(prod_df, n: int = 16) -> go.Figure:
    df = prod_df.sort_values("profit", ascending=True).tail(n)
    colors = [PALETTE["pink"] if p < 0 else PALETTE["green"] for p in df["profit"]]
    fig = go.Figure(go.Bar(
        x=df["profit"], y=df["product_name"], orientation="h",
        marker_color=colors,
        text=[f"${v:,.0f}" for v in df["profit"]],
        textposition="outside", textfont=dict(size=8),
        customdata=np.stack([df["category"].values, df["revenue"].values,
                             df["margin"].values], axis=-1),
        hovertemplate=("<b>%{y}</b><br>Profit: $%{x:,.0f}<br>"
                       "Category: %{customdata[0]}<br>"
                       "Revenue: $%{customdata[1]:,.0f}<br>"
                       "Margin: %{customdata[2]:.1f}%<extra></extra>"),
    ))
    fig.update_layout(**base_layout(height=340))
    fig.update_layout(xaxis_tickprefix="$", yaxis_tickfont=dict(size=8),
                      margin=dict(l=8, r=70, t=8, b=8))
    fig.add_vline(x=0, line_color=PALETTE["border"], line_width=1.5)
    return fig


def margin_vs_discount(cat_df) -> go.Figure:
    fig = go.Figure()
    fig.add_trace(go.Bar(
        x=cat_df["category"], y=cat_df["avg_discount"], name="Avg Discount %",
        marker_color=PALETTE["yellow"],
        hovertemplate="%{x}<br>Avg Discount: %{y:.1f}%<extra></extra>",
    ))
    colors = [PALETTE["pink"] if m < 0 else PALETTE["green"] for m in cat_df["margin"]]
    fig.add_trace(go.Bar(
        x=cat_df["category"], y=cat_df["margin"], name="Profit Margin %",
        marker_color=colors,
        hovertemplate="%{x}<br>Margin: %{y:.1f}%<extra></extra>",
    ))
    fig.update_layout(**base_layout(height=250))
    fig.update_layout(barmode="group", yaxis_ticksuffix="%",
                      xaxis_tickfont=dict(size=9))
    fig.add_hline(y=0, line_color=PALETTE["border"], line_width=1.5)
    return fig


def waterfall_chart(leak: dict, net_profit: float) -> go.Figure:
    names = ["Revenue", "Discounts", "Returns", "Shipping\n(success)", "Failed\nDelivery",
             "Pay Fees", "Net Profit"]
    values = [leak["revenue"], -leak["discounts"], -leak["returns"],
              -leak["shipping_success"], -leak["failed"], -leak["fees"], net_profit]
    kinds = ["total", "loss", "loss", "loss", "loss", "loss", "profit"]
    colors = [PALETTE["green"] if k == "total" else
              PALETTE["green_mid"] if k == "profit" else PALETTE["pink_deep"]
              for k in kinds]
    fig = go.Figure(go.Bar(
        x=names, y=values, marker_color=colors,
        text=[f"${abs(v):,.0f}" for v in values],
        textposition="outside", textfont=dict(size=8),
        hovertemplate="%{x}: $%{y:,.0f}<extra></extra>",
    ))
    fig.update_layout(**base_layout(height=280))
    fig.update_layout(yaxis_tickprefix="$", xaxis_tickfont=dict(size=8))
    return fig


def discount_margin_scatter(sample_df) -> go.Figure:
    df = sample_df.copy()
    df["band"] = np.where(df["profit_margin_percent"] < 0, "Negative",
                   np.where(df["profit_margin_percent"] < 10, "Low (<10%)", "Healthy"))
    color_map = {"Negative": PALETTE["pink"], "Low (<10%)": PALETTE["yellow"],
                 "Healthy": "#d8ec7a"}
    fig = px.scatter(
        df, x="discount_percent", y="profit_margin_percent", color="band",
        color_discrete_map=color_map,
        hover_data={"product_name": True, "category": True,
                    "total_price_usd": ":,.0f", "profit_usd": ":,.0f"},
        opacity=0.65,
    )
    fig.update_layout(**base_layout(height=280))
    fig.update_layout(xaxis_title="Discount %", yaxis_title="Profit Margin %",
                      yaxis_ticksuffix="%", xaxis_ticksuffix="%",
                      legend_title_text="")
    fig.add_hline(y=0, line_color=PALETTE["pink_deep"], line_dash="dash", line_width=1.2)
    fig.add_vline(x=25, line_color=PALETTE["yellow_deep"], line_dash="dash",
                  line_width=1.2,
                  annotation_text="25% threshold", annotation_font_size=9)
    fig.update_traces(marker=dict(size=6, line=dict(width=0)))
    return fig


def customer_value_scatter(cust_df, n: int = 3000) -> go.Figure:
    df = cust_df if len(cust_df) <= n else cust_df.sample(n, random_state=7)
    fig = px.scatter(
        df, x="revenue", y="profit", color="segment",
        color_discrete_map=SEGMENT_COLORS,
        hover_data={"customer_name": True, "country": True, "orders": True,
                    "clv": ":,.0f"},
        opacity=0.7,
    )
    fig.update_layout(**base_layout(height=270))
    fig.update_layout(xaxis_title="Customer Revenue (USD)",
                      yaxis_title="Customer Profit (USD)",
                      xaxis_tickprefix="$", yaxis_tickprefix="$",
                      legend_title_text="Segment")
    fig.update_traces(marker=dict(size=7, line=dict(width=0)))
    return fig


def clv_bars(cust_df, n: int = 14) -> go.Figure:
    df = cust_df.sort_values("clv", ascending=True).tail(n)
    colors = [SEGMENT_COLORS.get(s, PALETTE["green"]) for s in df["segment"]]
    fig = go.Figure(go.Bar(
        x=df["clv"], y=df["customer_name"], orientation="h",
        marker_color=colors,
        text=[f"${v:,.0f}" for v in df["clv"]],
        textposition="outside", textfont=dict(size=8),
        customdata=np.stack([df["country"].values, df["revenue"].values,
                             df["orders"].values], axis=-1),
        hovertemplate=("<b>%{y}</b><br>CLV (profit): $%{x:,.0f}<br>"
                       "%{customdata[0]} · Revenue $%{customdata[1]:,.0f} · "
                       "%{customdata[2]:,.0f} orders<extra></extra>"),
    ))
    fig.update_layout(**base_layout(height=300))
    fig.update_layout(xaxis_tickprefix="$", yaxis_tickfont=dict(size=8),
                      margin=dict(l=8, r=70, t=8, b=8))
    return fig


def shipping_cost_bars(ship_df, n: int = 10) -> go.Figure:
    df = ship_df.sort_values("shipping_cost", ascending=True).tail(n)
    fig = go.Figure(go.Bar(
        x=df["shipping_cost"], y=df["shipping_country"], orientation="h",
        marker_color="#b8cef8",
        text=[f"${v:,.0f}" for v in df["shipping_cost"]],
        textposition="outside", textfont=dict(size=8),
        hovertemplate="%{y}<br>Shipping: $%{x:,.0f}<extra></extra>",
    ))
    fig.update_layout(**base_layout(height=280))
    fig.update_layout(xaxis_tickprefix="$", yaxis_tickfont=dict(size=9),
                      margin=dict(l=8, r=70, t=8, b=8))
    return fig


def delivery_performance_bars(ship_df, n: int = 10) -> go.Figure:
    df = ship_df.sort_values("shipping_cost", ascending=False).head(n)
    df = df.sort_values("avg_days", ascending=True)
    fig = go.Figure()
    fig.add_trace(go.Bar(
        x=df["avg_days"], y=df["shipping_country"], orientation="h",
        name="Avg Delivery Days", marker_color="#b8cef8",
        hovertemplate="%{y}<br>Avg days: %{x:.1f}<extra></extra>",
    ))
    fig.add_trace(go.Bar(
        x=df["failed_pct"], y=df["shipping_country"], orientation="h",
        name="Failed Delivery %", marker_color="#f4b8d0",
        hovertemplate="%{y}<br>Failed: %{x:.1f}%<extra></extra>",
    ))
    fig.update_layout(**base_layout(height=280))
    fig.update_layout(barmode="group", yaxis_tickfont=dict(size=9),
                      margin=dict(l=8, r=8, t=30, b=8))
    return fig


def leakage_sources_bars(leak: dict) -> go.Figure:
    import pandas as pd
    rows = [
        ("Discounts", leak["discounts"], PALETTE["pink_deep"]),
        ("Returns", leak["returns"], PALETTE["yellow_deep"]),
        ("Shipping", leak["shipping"], PALETTE["blue"]),
        ("Failed Delivery", leak["failed"], PALETTE["green"]),
        ("Payment Fees (est.)", leak["fees"], PALETTE["pink"]),
    ]
    data = pd.DataFrame(rows, columns=["source", "amount", "color"])
    fig = go.Figure(go.Bar(
        x=data["amount"], y=data["source"], orientation="h",
        marker_color=data["color"],
        text=[f"${v:,.0f}" for v in data["amount"]],
        textposition="outside", textfont=dict(size=9),
        hovertemplate="%{y}: $%{x:,.0f}<extra></extra>",
    ))
    fig.update_layout(**base_layout(height=230))
    fig.update_layout(xaxis_tickprefix="$", margin=dict(l=8, r=70, t=8, b=8))
    return fig

# ======================================================================
# components/tables.py
# ======================================================================

"""Sortable DataTables with pastel styling."""


from dash import dash_table

TABLE_STYLE_HEADER = {
    "backgroundColor": "#f8f9fc",
    "color": "#5A5C72",
    "fontWeight": "600",
    "fontSize": "11px",
    "border": "none",
    "borderBottom": "2px solid #eceacc",
    "padding": "8px 12px",
}
TABLE_STYLE_CELL = {
    "fontSize": "12px",
    "fontFamily": "Inter, system-ui, sans-serif",
    "color": "#2C2E45",
    "padding": "9px 12px",
    "border": "none",
    "borderBottom": "1px solid #eceacc",
    "textAlign": "left",
}
TABLE_STYLE_TABLE = {"overflowX": "auto", "borderRadius": "12px"}


def sortable_table(
    table_id: str,
    columns: list[dict],
    data: list[dict],
    page_size: int = 12,
    extra_style: dict | None = None,
):
    return dash_table.DataTable(
        id=table_id,
        columns=columns,
        data=data,
        sort_action="native",
        filter_action="native",
        page_action="native",
        page_size=page_size,
        style_header=TABLE_STYLE_HEADER,
        style_cell=TABLE_STYLE_CELL,
        style_table={**TABLE_STYLE_TABLE, **(extra_style or {})},
        style_data_conditional=[
            {"if": {"row_index": "odd"}, "backgroundColor": "#FAFBFE"},
        ],
        filter_options={"case": "insensitive"},
    )

# ======================================================================
# pages/executive_overview.py
# ======================================================================

"""Page 1 — Executive Overview (mirrors React layout, values from dataset, USD)."""


from dash import html, dcc



def executive_overview_layout(agg: dict):
    totals = agg["totals"]
    leak = agg["leakage"]
    trend = agg["trend"]
    country = agg["country"]
    category = agg["category"]
    products = agg["products"]

    hero = html.Div(
        className="hero",
        children=[
            html.Div(children=[
                html.Div("FY 2024–2026 · Executive Summary", className="hero-eyebrow"),
                html.Div(
                    f"{fmt_usd_compact(leak['total'])} in Profit Leakage Identified",
                    className="hero-title",
                ),
                html.Div(
                    f"{fmt_pct(leak['total_pct'])} of revenue lost to discounts, "
                    "returns, shipping and fees",
                    className="hero-sub",
                ),
            ]),
            html.Div(
                className="hero-right",
                children=[
                    html.Div("Net Profit Margin".upper(), className="hero-eyebrow"),
                    html.Div(
                        fmt_pct(
                            totals["net_profit"] / totals["revenue"] * 100
                            if totals["revenue"] else 0
                        ),
                        className="hero-margin",
                    ),
                    html.Div(
                        f"{fmt_usd_compact(totals['net_profit'])} of "
                        f"{fmt_usd_compact(totals['revenue'])} revenue",
                        className="hero-sub",
                    ),
                ],
            ),
        ],
    )

    # Product table data (top 12 by profit)
    prod_top = products.sort_values("profit", ascending=False).head(12)
    prod_cols = [
        {"name": "Product", "id": "product_name"},
        {"name": "Category", "id": "category"},
        {"name": "Revenue (USD)", "id": "revenue_fmt", "type": "numeric"},
        {"name": "Profit (USD)", "id": "profit_fmt", "type": "numeric"},
        {"name": "Margin %", "id": "margin", "type": "numeric",
         "format": {"specifier": ".1f"}},
        {"name": "Avg Discount %", "id": "avg_discount", "type": "numeric",
         "format": {"specifier": ".1f"}},
        {"name": "Return Rate %", "id": "return_rate", "type": "numeric",
         "format": {"specifier": ".1f"}},
    ]
    prod_data = [
        {
            "product_name": r.product_name, "category": r.category,
            "revenue_fmt": fmt_usd(r.revenue), "profit_fmt": fmt_usd(r.profit),
            "margin": round(r.margin, 1),
            "avg_discount": round(r.avg_discount, 1),
            "return_rate": round(r.return_rate, 1),
        }
        for r in prod_top.itertuples()
    ]

    return html.Div(
        className="page",
        children=[
            hero,
            kpi_row_from_totals(totals),
            html.Div(
                className="grid-37-63",
                children=[
                    card(
                        "Revenue vs Profit Trend",
                        "Monthly revenue and gross profit from order_date",
                        [dcc.Graph(figure=revenue_profit_trend(trend),
                                   style={"width": "100%", "height": "100%"},
                                   config={"displayModeBar": False,
                                           "responsive": True})],
                    ),
                    card(
                        "Profit by Country",
                        "Country fill represents profit · pink = negative",
                        [dcc.Graph(figure=profit_world_map(country),
                                   className="map-viewport",
                                   style={"width": "100%", "height": "100%"},
                                   config={"responsive": True,
                                           "scrollZoom": True,
                                           "displayModeBar": True,
                                           "doubleClick": "reset"})],
                    ),
                ],
            ),
            html.Div(
                className="grid-2",
                children=[
                    card(
                        "Profit Leakage Sources",
                        f"{fmt_usd_compact(leak['total'])} identified across "
                        "discounts, returns, shipping and fees",
                        [dcc.Graph(figure=leakage_sources_bars(leak),
                                   config={"displayModeBar": False})],
                    ),
                    card(
                        "Profit by Category",
                        "Positive green · negative pink",
                        [dcc.Graph(figure=category_profit_bars(category),
                                   config={"displayModeBar": False})],
                    ),
                ],
            ),
            card(
                "Product Profitability",
                "Top 12 products by profit · sortable and filterable · USD",
                [sortable_table("exec-products", prod_cols, prod_data,
                                page_size=12)],
            ),
        ],
    )

# ======================================================================
# pages/profit_leakage.py
# ======================================================================

"""Page 2 — Profit Leakage (breakdown, waterfall, scatter, global shipping)."""


from dash import html, dcc



def _severity(pct: float) -> tuple[str, str]:
    if pct >= 4:
        return "Critical", "#c8608a"
    if pct >= 2:
        return "High", "#d4b800"
    if pct >= 1:
        return "Medium", "#9abe30"
    return "Low", "#6ec8f0"


def profit_leakage_layout(agg: dict):
    totals = agg["totals"]
    leak = agg["leakage"]
    ship = agg["shipping"]
    scatter = agg["scatter"]

    drivers = {
        "Discounts": "Highest avg discount categories",
        "Returns / Refunds": "order_status = Returned",
        "Shipping Costs": "All shipments",
        "Failed Deliveries": "delivery_status = Failed (shipping wasted)",
        "Payment Fees (est.)": "Estimated by payment_method",
    }
    rows = [
        ("Discounts", leak["discounts"], leak["discounts_pct"]),
        ("Returns / Refunds", leak["returns"], leak["returns_pct"]),
        ("Shipping Costs", leak["shipping"], leak["shipping_pct"]),
        ("Failed Deliveries", leak["failed"], leak["failed_pct"]),
        ("Payment Fees (est.)", leak["fees"], leak["fees_pct"]),
    ]
    leak_cols = [
        {"name": "Source", "id": "source"},
        {"name": "Amount (USD)", "id": "amount"},
        {"name": "% Revenue", "id": "pct"},
        {"name": "Severity", "id": "severity"},
        {"name": "Primary Driver", "id": "driver"},
    ]
    leak_data = []
    for src, amt, pct in rows:
        sev, _ = _severity(pct)
        leak_data.append({
            "source": src, "amount": fmt_usd(amt), "pct": fmt_pct(pct),
            "severity": sev, "driver": drivers[src],
        })

    # Shipping summary cards (computed)
    top_cost = ship.iloc[0]
    top_failed = ship.sort_values("failed_pct", ascending=False).iloc[0]
    top_orders = ship.sort_values("orders", ascending=False).iloc[0]
    top_days = ship.sort_values("avg_days", ascending=False).iloc[0]

    return html.Div(
        className="page",
        children=[
            card(
                "Profit Leakage Breakdown",
                f"Revenue: {fmt_usd_compact(leak['revenue'])} · "
                f"Identified leakage: {fmt_usd_compact(leak['total'])} · "
                f"Net profit: {fmt_usd_compact(totals['net_profit'])} "
                "(fees estimated by payment method)",
                [sortable_table("leak-breakdown", leak_cols, leak_data,
                                page_size=6)],
            ),
            html.Div(
                className="grid-2",
                children=[
                    card(
                        "Revenue to Profit Waterfall",
                        "Revenue minus leakage components to net profit "
                        "(shipping split: successful vs failed)",
                        [dcc.Graph(
                            figure=waterfall_chart(leak, totals["net_profit"]),
                            config={"displayModeBar": False})],
                    ),
                    card(
                        "Discount vs Profit Margin",
                        "Each point is a sampled order · discount_percent vs "
                        "profit_margin_percent",
                        [dcc.Graph(figure=discount_margin_scatter(scatter),
                                   config={"displayModeBar": False})],
                    ),
                ],
            ),
            card(
                "Global Shipping and Delivery Analysis",
                "Geography uses shipping_country · country fill = shipping cost",
                children=[
                    dcc.Graph(figure=shipping_world_map(ship),
                              className="map-viewport",
                              style={"width": "100%", "height": "100%"},
                              config={"responsive": True,
                                      "scrollZoom": True,
                                      "displayModeBar": True,
                                      "doubleClick": "reset"}),
                    html.Div(
                        className="summary-row",
                        children=[
                            summary_card(
                                "Highest Shipping Cost",
                                fmt_usd_compact(top_cost["shipping_cost"]),
                                f"{top_cost['shipping_country']} · "
                                f"{fmt_int(top_cost['orders'])} orders",
                                kind="blue"),
                            summary_card(
                                "Highest Failed Delivery Rate",
                                fmt_pct(top_failed["failed_pct"]),
                                f"{top_failed['shipping_country']} · "
                                f"{fmt_pct(top_failed['failed_pct'])} failed",
                                kind="pink"),
                            summary_card(
                                "Highest Order Volume",
                                fmt_int(top_orders["orders"]),
                                f"{top_orders['shipping_country']}",
                                kind="green"),
                            summary_card(
                                "Longest Average Delivery",
                                f"{top_days['avg_days']:.1f} days",
                                f"{top_days['shipping_country']}",
                                kind="yellow"),
                        ],
                    ),
                    html.Div(
                        className="grid-2",
                        children=[
                            html.Div(children=[
                                html.Div("Shipping Cost by Country",
                                         className="mini-title"),
                                html.Div("Total shipping spend in USD",
                                         className="card-sub"),
                                dcc.Graph(figure=shipping_cost_bars(ship),
                                          config={"displayModeBar": False}),
                            ]),
                            html.Div(children=[
                                html.Div("Delivery Performance by Country",
                                         className="mini-title"),
                                html.Div("Average delivery days vs failed rate",
                                         className="card-sub"),
                                dcc.Graph(
                                    figure=delivery_performance_bars(ship),
                                    config={"displayModeBar": False}),
                            ]),
                        ],
                    ),
                ],
            ),
        ],
    )

# ======================================================================
# pages/customer_value.py
# ======================================================================

"""Page 3 — Customer Value (segments from actual profitability tertiles)."""


from dash import html, dcc



def _segment_cards(cust):
    cards = []
    for seg, kind in [("High", "green"), ("Medium", "blue"), ("Low", "pink")]:
        sub = cust[cust["segment"] == seg]
        n = len(sub)
        rev = sub["revenue"].sum()
        prof = sub["profit"].sum()
        avg_clv = sub["clv"].mean() if n else 0
        avg_aov = sub["aov"].mean() if n else 0
        dot = {"green": "#9abe30", "blue": "#6ec8f0", "pink": "#c8608a"}[kind]
        cards.append(
            html.Div(
                className="card seg-card",
                children=[
                    html.Div(
                        className="seg-head",
                        children=[
                            html.Span(className="nav-dot",
                                      style={"background": dot,
                                             "width": "12px", "height": "12px"}),
                            html.Div(children=[
                                html.Div(f"{seg} Value", className="card-title"),
                                html.Div(f"{fmt_int(n)} customers",
                                         className="card-sub"),
                            ]),
                        ],
                    ),
                    html.Div(
                        className="seg-grid",
                        children=[
                            html.Div(children=[
                                html.Div("Revenue", className="kpi-sub"),
                                html.Div(fmt_usd_compact(rev),
                                         className="seg-val"),
                            ]),
                            html.Div(children=[
                                html.Div("Profit", className="kpi-sub"),
                                html.Div(fmt_usd_compact(prof),
                                         className="seg-val"),
                            ]),
                            html.Div(children=[
                                html.Div("Avg CLV", className="kpi-sub"),
                                html.Div(fmt_usd(avg_clv),
                                         className="seg-val"),
                            ]),
                            html.Div(children=[
                                html.Div("Avg AOV", className="kpi-sub"),
                                html.Div(fmt_usd(avg_aov),
                                         className="seg-val"),
                            ]),
                        ],
                    ),
                ],
            )
        )
    return html.Div(cards, className="seg-row")


def customer_value_layout(agg: dict):
    cust = agg["customers"]
    top = cust.sort_values("clv", ascending=False).head(50)

    cols = [
        {"name": "Customer", "id": "customer_name"},
        {"name": "Segment", "id": "segment"},
        {"name": "Country", "id": "country"},
        {"name": "Revenue (USD)", "id": "revenue"},
        {"name": "Profit (USD)", "id": "profit"},
        {"name": "Orders", "id": "orders", "type": "numeric"},
        {"name": "AOV (USD)", "id": "aov"},
        {"name": "Return Rate %", "id": "return_rate", "type": "numeric",
         "format": {"specifier": ".1f"}},
        {"name": "CLV / Profit (USD)", "id": "clv"},
    ]
    data = [
        {
            "customer_name": r.customer_name, "segment": r.segment,
            "country": r.country,
            "revenue": fmt_usd(r.revenue), "profit": fmt_usd(r.profit),
            "orders": int(r.orders), "aov": fmt_usd(r.aov),
            "return_rate": round(r.return_rate, 1), "clv": fmt_usd(r.clv),
        }
        for r in top.itertuples()
    ]

    seg_counts = cust["segment"].value_counts().to_dict()
    seg_note = (
        f"Segments derived from customer profit tertiles · "
        f"High {fmt_int(seg_counts.get('High', 0))} · "
        f"Medium {fmt_int(seg_counts.get('Medium', 0))} · "
        f"Low {fmt_int(seg_counts.get('Low', 0))} · "
        f"{fmt_int(len(cust))} customers total"
    )

    return html.Div(
        className="page",
        children=[
            _segment_cards(cust),
            html.Div(children=[seg_note], className="note"),
            html.Div(
                className="grid-2",
                children=[
                    card(
                        "Customer Value Map",
                        "X = customer revenue · Y = customer profit · "
                        "color = High / Medium / Low",
                        [dcc.Graph(figure=customer_value_scatter(cust),
                                   config={"displayModeBar": False})],
                    ),
                    card(
                        "Customer Lifetime Value",
                        "Top customers by lifetime profit (CLV proxy)",
                        [dcc.Graph(figure=clv_bars(cust),
                                   config={"displayModeBar": False})],
                    ),
                ],
            ),
            card(
                "Customer Detail — Value, Behaviour and Profitability",
                "Top 50 by CLV · sortable and filterable · USD",
                [sortable_table("cust-detail", cols, data, page_size=12)],
            ),
        ],
    )

# ======================================================================
# pages/product_analysis.py
# ======================================================================

"""Page 4 — Product Analysis (category + product, all from dataset)."""


from dash import html, dcc



def product_analysis_layout(agg: dict):
    category = agg["category"]
    products_ranked = agg["products_ranked"]
    products = agg["products"]

    # Dataset is uniform at product level (all margins ~39.7-40.1%), so an
    # absolute <10% filter always returns 0 rows. Show lowest-margin products.
    low = products.sort_values("margin").head(12)

    def issue(r) -> str:
        if r.avg_discount > 30:
            return "Over-discounted"
        if r.return_rate > 18:
            return "High returns"
        if r.profit < 0:
            return "Margin-negative"
        return "Low margin"

    cols = [
        {"name": "Product", "id": "product_name"},
        {"name": "Category", "id": "category"},
        {"name": "Revenue (USD)", "id": "revenue"},
        {"name": "Profit (USD)", "id": "profit"},
        {"name": "Margin %", "id": "margin", "type": "numeric",
         "format": {"specifier": ".1f"}},
        {"name": "Avg Discount %", "id": "avg_discount", "type": "numeric",
         "format": {"specifier": ".1f"}},
        {"name": "Return Rate %", "id": "return_rate", "type": "numeric",
         "format": {"specifier": ".1f"}},
        {"name": "Issue", "id": "issue"},
    ]
    data = [
        {
            "product_name": r.product_name, "category": r.category,
            "revenue": fmt_usd(r.revenue), "profit": fmt_usd(r.profit),
            "margin": round(r.margin, 1),
            "avg_discount": round(r.avg_discount, 1),
            "return_rate": round(r.return_rate, 1),
            "issue": issue(r),
        }
        for r in low.itertuples()
    ]

    return html.Div(
        className="page",
        children=[
            html.Div(
                className="grid-2",
                children=[
                    card(
                        "Category: Revenue vs Profit",
                        "Revenue and profit summed from profit_usd · USD",
                        [dcc.Graph(figure=category_revenue_profit(category),
                                   config={"displayModeBar": False})],
                    ),
                    card(
                        "Product Profitability Ranking",
                        "Top winners and worst losers by profit_usd · "
                        "green = positive, pink = negative",
                        [dcc.Graph(figure=product_ranking_bars(products_ranked),
                                   config={"displayModeBar": False})],
                    ),
                ],
            ),
            card(
                "Category: Profit Margin vs Avg Discount",
                "Average discount_percent against realized profit margin",
                [dcc.Graph(figure=margin_vs_discount(category),
                           config={"displayModeBar": False})],
            ),
            html.Div(
                className="card alert-card",
                children=[
                    html.Div(
                        className="alert-head",
                        children=[
                            html.Span("Action Required", className="alert-pill"),
                            html.Span("Low / Negative Margin Products",
                                      className="card-title"),
                        ],
                    ),
                    html.Div(
                        "Lowest-margin products by realized margin · computed from "
                        "revenue, profit, discount and returns",
                        className="card-sub",
                    ),
                    html.Div(children=[
                        sortable_table("low-margin", cols, data, page_size=12)
                    ], className="card-body"),
                ],
            ),
        ],
    )

# ======================================================================
# app.py
# ======================================================================

"""ProfitLens — Global E-Commerce Profit Leakage & Customer Value Analytics.

Python / Dash / Plotly / Pandas implementation.
Loads the dataset ONCE at startup, precomputes all aggregates,
then serves 4 pages from memory (no per-page reloads).

Run:
    python app.py            # dev server on http://127.0.0.1:8050
"""


import traceback

from dash import Dash, html, dcc, Input, Output


TITLE_MAP = {
    "/": ("Executive Overview", "Executive Overview"),
    "/leakage": ("Profit Leakage", "Profit Leakage"),
    "/customers": ("Customer Value", "Customer Value"),
    "/products": ("Product Analysis", "Product Analysis"),
}

print("Loading Global E-Commerce dataset (once) ...", flush=True)
try:
    DF = load_dataset()
    print(f"Dataset ready: {len(DF):,} rows.", flush=True)
except Exception as exc:
    print(f"DATASET LOAD FAILED: {exc}", flush=True)
    traceback.print_exc()
    raise

print("Precomputing aggregates ...", flush=True)
AGG = get_aggregates(DF)
print("Aggregates ready.", flush=True)

app = Dash(
    __name__,
    title="ProfitLens Analytics Suite",
    suppress_callback_exceptions=True,
)
server = app.server

app.layout = html.Div(
    className="app-shell",
    children=[
        dcc.Location(id="url", refresh=False),
        html.Div(id="sidebar-wrap"),
        html.Div(
            className="main",
            children=[
                html.Div(id="header-wrap"),
                html.Main(id="page-content", className="content"),
            ],
        ),
    ],
)


@app.callback(
    Output("sidebar-wrap", "children"),
    Output("header-wrap", "children"),
    Output("page-content", "children"),
    Input("url", "pathname"),
)
def render_page(pathname: str | None):
    path = pathname or "/"
    title, crumb = TITLE_MAP.get(path, TITLE_MAP["/"])
    if path == "/leakage":
        page = profit_leakage_layout(AGG)
    elif path == "/customers":
        page = customer_value_layout(AGG)
    elif path == "/products":
        page = product_analysis_layout(AGG)
    else:
        path = "/"
        title, crumb = TITLE_MAP["/"]
        page = executive_overview_layout(AGG)
    return sidebar(path), page_header(title, crumb), page


if __name__ == "__main__":
    app.run(debug=True, host="127.0.0.1", port=8050)
